integrations:
  - name: nri-flex
    config:
      name: SolaceCompleteIntegration
      interval: "5s"
      
      apis:            # Dynamic discovery of VPNs
        - name: SolaceDiscoverVPNs
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py discover-vpns"
              split_by: ":\n"
          store_variables:
            vpn_list: "$env_SOLACE_VPN_LIST" # Will be set by the Python script
          custom_attributes:
            event_type: SolaceVPNSummary
            provider: solace
            
        # Dynamic discovery of Queues in each VPN
        - name: SolaceDiscoverQueues 
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py discover-queues-all"
              split_by: ":\n"
              timeout: 60000 # Increase timeout to 60 seconds
          custom_attributes:
            event_type: SolaceQueueSummary
            provider: solace
            resourcetype: queue

        # Queue Statistics for each queue in each vpn
        - name: SolaceQueueStats
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py queue-stats-all"
              # Using ":\n" as a separator to match cohesity.yaml example
              split_by: ":\n" 
              timeout: 60000 # Increase timeout to 60 seconds
          custom_attributes:
            event_type: SolaceQueueStats
            provider: solace
            resourcetype: queue
        
        # VPN Statistics for each VPN
        - name: SolaceVPNStats 
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py vpn-stats-all"
              # Using ":\n" as a separator to match cohesity.yaml example
              split_by: ":\n"
              timeout: 60000 # Increase timeout to 60 seconds
          custom_attributes:
            event_type: SolaceVPNDetailedMetrics
            provider: solace
            
        # Topic Endpoint discovery and stats
        - name: SolaceTopicEndpoints
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py discover-topic-endpoints-all"
              # Using ":\n" as a separator to match cohesity.yaml example
              split_by: ":\n"
              timeout: 60000 # Increase timeout to 60 seconds
          custom_attributes:
            event_type: SolaceTopicEndpointMetrics
            provider: solace
            resourcetype: topicEndpoint
            
        # Bridge Statistics for each VPN
        - name: SolaceBridgeStats
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py bridge-stats-all"
              # Using ":\n" as a separator to match cohesity.yaml example
              split_by: ":\n"
              timeout: 60000 # Increase timeout to 60 seconds
          custom_attributes:
            event_type: SolaceBridgeMetrics
            provider: solace
            resourcetype: bridge
            
        # Client Statistics for each VPN
        - name: SolaceClientStats
          commands:
            - run: "${PYTHON_PATH:-python3} /usr/bin/entrypoint.py client-stats-all"
              # Using ":\n" as a separator to match cohesity.yaml example
              split_by: ":\n"
              timeout: 60000 # Increase timeout to 60 seconds
          custom_attributes:
            event_type: SolaceClientMetrics
            provider: solace
            resourcetype: client